name = "MechEq"
uuid = "eaab1d0a-c535-4993-bcc2-e478e0840793"
authors = ["tim-au <99239974+tim-au@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
